name: Compile C# App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            3.1.x
            4.6.x
            5.0.x
      - run: dotnet build IsoCreatorTool.sln


      - name: Upload Windows artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-executable
          path: .
